version = 0.1
[default.deploy.parameters]
stack_name = "gptea-api-test"
resolve_s3 = true
s3_prefix = "gptea-api-test"
region = "ap-northeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"test\""
image_repositories = []
